# Generated by Django 4.2.5 on 2024-04-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_text_uz', models.CharField(max_length=200)),
                ('carousel_text_uz_uz', models.CharField(max_length=200, null=True)),
                ('carousel_text_uz_en', models.CharField(max_length=200, null=True)),
                ('carousel_text_uz_ru', models.CharField(max_length=200, null=True)),
                ('carousel_subtext_uz', models.CharField(max_length=250)),
                ('carousel_subtext_uz_uz', models.CharField(max_length=250, null=True)),
                ('carousel_subtext_uz_en', models.CharField(max_length=250, null=True)),
                ('carousel_subtext_uz_ru', models.CharField(max_length=250, null=True)),
                ('carousel_photo', models.ImageField(upload_to='carousel/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_theme_uz', models.CharField(max_length=200)),
                ('news_theme_uz_uz', models.CharField(max_length=200, null=True)),
                ('news_theme_uz_en', models.CharField(max_length=200, null=True)),
                ('news_theme_uz_ru', models.CharField(max_length=200, null=True)),
                ('news_short_description_uz', models.TextField()),
                ('news_short_description_uz_uz', models.TextField(null=True)),
                ('news_short_description_uz_en', models.TextField(null=True)),
                ('news_short_description_uz_ru', models.TextField(null=True)),
                ('news_full_description_uz', models.TextField()),
                ('news_full_description_uz_uz', models.TextField(null=True)),
                ('news_full_description_uz_en', models.TextField(null=True)),
                ('news_full_description_uz_ru', models.TextField(null=True)),
                ('news_photo', models.ImageField(upload_to='news/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_link', models.CharField(max_length=200)),
                ('partner_photo', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_uz', models.CharField(max_length=100)),
                ('category_name_uz_uz', models.CharField(max_length=100, null=True)),
                ('category_name_uz_en', models.CharField(max_length=100, null=True)),
                ('category_name_uz_ru', models.CharField(max_length=100, null=True)),
                ('category_text_uz', models.CharField(max_length=250)),
                ('category_text_uz_uz', models.CharField(max_length=250, null=True)),
                ('category_text_uz_en', models.CharField(max_length=250, null=True)),
                ('category_text_uz_ru', models.CharField(max_length=250, null=True)),
                ('category_photo', models.ImageField(upload_to='projects_category/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name_uz', models.CharField(max_length=100)),
                ('video_name_uz_uz', models.CharField(max_length=100, null=True)),
                ('video_name_uz_en', models.CharField(max_length=100, null=True)),
                ('video_name_uz_ru', models.CharField(max_length=100, null=True)),
                ('video_text_uz', models.CharField(max_length=200)),
                ('video_text_uz_uz', models.CharField(max_length=200, null=True)),
                ('video_text_uz_en', models.CharField(max_length=200, null=True)),
                ('video_text_uz_ru', models.CharField(max_length=200, null=True)),
                ('video_file', models.FileField(upload_to='project_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fullname_uz', models.CharField(max_length=50)),
                ('student_fullname_uz_uz', models.CharField(max_length=50, null=True)),
                ('student_fullname_uz_en', models.CharField(max_length=50, null=True)),
                ('student_fullname_uz_ru', models.CharField(max_length=50, null=True)),
                ('student_info_uz', models.CharField(max_length=200)),
                ('student_info_uz_uz', models.CharField(max_length=200, null=True)),
                ('student_info_uz_en', models.CharField(max_length=200, null=True)),
                ('student_info_uz_ru', models.CharField(max_length=200, null=True)),
                ('student_photo', models.ImageField(upload_to='students/')),
                ('student_link1', models.CharField(max_length=100)),
                ('student_link2', models.CharField(max_length=100)),
                ('student_link3', models.CharField(max_length=100)),
                ('student_link4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name_uz', models.CharField(max_length=100)),
                ('project_name_uz_uz', models.CharField(max_length=100, null=True)),
                ('project_name_uz_en', models.CharField(max_length=100, null=True)),
                ('project_name_uz_ru', models.CharField(max_length=100, null=True)),
                ('project_subtext_uz', models.CharField(max_length=250)),
                ('project_subtext_uz_uz', models.CharField(max_length=250, null=True)),
                ('project_subtext_uz_en', models.CharField(max_length=250, null=True)),
                ('project_subtext_uz_ru', models.CharField(max_length=250, null=True)),
                ('project_text_uz', models.TextField()),
                ('project_text_uz_uz', models.TextField(null=True)),
                ('project_text_uz_en', models.TextField(null=True)),
                ('project_text_uz_ru', models.TextField(null=True)),
                ('project_photo', models.ImageField(upload_to='projects/')),
                ('project_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.projectscategorymodel')),
            ],
        ),
    ]
